name: Test

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./01"
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - run: nix build
    - run: nix flake check
